"""CodeSentinel — Output Formatter."""

from __future__ import annotations

from app.models.schemas import ReviewReport


def format_markdown(report: ReviewReport) -> str:
    """Format a review report as Markdown.

    Args:
        report: Complete review report.

    Returns:
        Markdown-formatted string.
    """
    parts = [
        f"# 🛡️ CodeSentinel Review — `{report.filename}`",
        "",
        f"**Overall Score: {report.overall_score}/10** | "
        f"**Issues Found: {report.total_issues}**",
        "",
    ]

    # Code stats
    if report.code_stats:
        stats = report.code_stats
        parts.extend([
            "## 📊 Code Statistics",
            f"- **Lines:** {stats.get('total_lines', 0)} "
            f"(blank: {stats.get('blank_lines', 0)}, "
            f"comments: {stats.get('comment_lines', 0)})",
            f"- **Functions:** {stats.get('functions', 0)}",
            f"- **Classes:** {stats.get('classes', 0)}",
            f"- **Avg Complexity:** {stats.get('avg_complexity', 0):.1f}",
            f"- **Max Complexity:** {stats.get('max_complexity', 0)}",
            "",
        ])

    # LLM review
    if report.llm_review:
        parts.extend([
            "## 🧠 AI Review",
            f"*{report.llm_review.summary}*",
            "",
        ])

        if report.llm_review.issues:
            parts.append("### Issues")
            for issue in report.llm_review.issues:
                severity_icon = {
                    "critical": "🔴",
                    "high": "🟠",
                    "medium": "🟡",
                    "low": "🟢",
                }.get(issue.severity, "⚪")

                line_info = f" (line {issue.lineno})" if issue.lineno else ""
                parts.extend([
                    f"#### {severity_icon} [{issue.severity.upper()}] {issue.title}{line_info}",
                    f"**Category:** {issue.category}",
                    f"> {issue.description}",
                    "",
                ])
                if issue.suggestion:
                    parts.append(f"💡 **Fix:** {issue.suggestion}")
                    parts.append("")

        if report.llm_review.improvements:
            parts.extend([
                "### ✅ Positives",
                *[f"- {imp}" for imp in report.llm_review.improvements],
                "",
            ])

    # Security findings
    if report.security_findings:
        parts.extend([
            "## 🔒 Security Findings",
            "",
        ])
        for finding in report.security_findings:
            severity_icon = {
                "critical": "🔴",
                "high": "🟠",
                "medium": "🟡",
                "low": "🟢",
            }.get(finding.get("severity", ""), "⚪")

            parts.extend([
                f"### {severity_icon} [{finding.get('rule_id', '')}] {finding.get('title', '')}",
                f"**Line {finding.get('lineno', '?')}:** `{finding.get('code_snippet', '')}`",
                f"> {finding.get('description', '')}",
                f"💡 {finding.get('recommendation', '')}",
                "",
            ])

    parts.append("---")
    parts.append("*Generated by CodeSentinel — AI-Powered Code Review*")

    return "\n".join(parts)


def format_json(report: ReviewReport) -> dict:
    """Format a review report as a JSON-compatible dict."""
    return report.model_dump()
